apiVersion: v1
kind: Pod
metadata:
  name: mon_projet_hetic 
  labels:
    app: web
spec:
  containers:
    - name: mariadb
      image: mariadb:latest 
      ports:
        - containerPort: 3306

    - name: phpmyadmin 
      image: phpmyadmin 
      ports:
        - containerPort: 40001

    - name: wordpress
      image: wordpress
      ports:
        - containerPort: 80
      env:
        - name: WORDPRESS_DB_HOST
          value: mariadb
        - name: WORDPRESS_DB_NAME
          value: heticdb
        - name: WORDPRESS_DB_USER
          value: hetic
        - name: WORDPRESS_DB_PASSWORD
          value: hetic
      volumeMounts:
        - name: wordpress
          mountPath: /var/www/html

    - name: web
      build: .
      command: ["python", "app.py"]
      ports:
        - containerPort: 80
      restart: always
      volumes:
        - hostPath:
            path: "/path/to/host/static"
          mountPath: "/app/static"