version: '3.8'
services:
  web:
    image: python:3.8-slim
    command: bash -c "pip install -r /app/requirements.txt && python /app/app.py"
    volumes:
      - ./app:/app
    expose:
      - 89
    ports:
      - "89:89"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
